project_id = "ugzrewnbpljswwboctfh"

[functions.setup-first-admin]
verify_jwt = false

[functions.create-external-reservation]
verify_jwt = false

[functions.create-external-equipment-request]
verify_jwt = false
